server:
  port: 8081

database:
  schema: dbo

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5432/demo?currentSchema=${database.schema}
    driver-class-name: org.postgresql.Driver
    username: admin
    password: admin
    hikari:
      schema: ${database.schema}
      connection-init-sql: CREATE SCHEMA IF NOT EXISTS "${database.schema}";
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: com.example.userservice.config.HibernateNamingStrategy
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
    default-schema: ${database.schema}
